### ISSUE TITLE
Documentation of the new PSN API?

### ISSUE THREAD

**Issue by Ragowit** [andshrew/PlayStation-Trophies#1]
First, truly great and detailed documentation of the API used by https://my.playstation.com

With the release of the new PSN app so is there a new base URL to access information with support for PS5 titles and other updated information as well, https://m.np.playstation.net/api/

So I simply wonder if you will take on the task to document this as well? At the time of this writing so does https://my.playstation.com still uses the old API and can't display PS5 titles.

**Comment by andshrew** [comment]
Hi @Ragowit, thanks for the feedback I appreciate that.

I'm interested in looking in to the new APIs but it might have to wait until they update https://my.playstation.com to use them as I have not found a way to be able to successfully capture the traffic of the app to see the calls it's making. It seems to communicate entirely over HTTPS and even when using a proxy so that I can do SSL inspection the app doesn't seem to use it properly.

**Comment by Ragowit** [comment]
There was a comment here that might help you, if you want to investigate further: https://github.com/Tustin/psn-php/issues/146#issuecomment-727098493

Otherwise it might be easiest to wait until they update the site, as you said.

**Comment by andshrew** [comment]
Just to let you know I've uploaded some initial documentation for the new API now.

Thanks for that link, it helped in understanding how to authenticate to the new API.

**Comment by Ragowit** [comment]
Looking good! Thanks for the update. I have found a "reward" attribute for trophies, and I have so far only encountered it with the game "Destruction AllStars". Easy to miss since its hard to find.

**Comment by andshrew** [comment]
Nice spot on that, I'll add in over the next few days.
